# Column space

In [1]:
# TASK 1: You have seen that the SVD of an m × n matrix A gives, among other things, a 
#basis for the range (column space). Compute this for the given matrix.

import numpy as np
from scipy.linalg import svd, qr

A = np.array([[1, -2, 3, -3], [2, -4, 9, -2], [-3, 6, -9, 9]])

# Using SVD to compute the basis for the column space
U, S, VT = svd(A)
basis_svd = U[:, :np.linalg.matrix_rank(A)]

# Using QR to compute the basis for the column space
Q, R = qr(A, mode='economic')
basis_qr = Q

# Print the bases for the column space
print("Basis for the Column Space using SVD:")
print(basis_svd)
print("\nBasis for the Column Space using QR:")
print(basis_qr)


Basis for the Column Space using SVD:
[[-0.26623586 -0.17064134]
 [-0.5396153   0.84191171]
 [ 0.79870758  0.51192403]]

Basis for the Column Space using QR:
[[-0.26726124  0.95140796  0.152952  ]
 [-0.53452248 -0.2784383   0.79797107]
 [ 0.80178373  0.13151046  0.58296471]]


# Explaination

1) svd(A) computes the Singular Value Decomposition of matrix A, and U, S, and VT contain the left singular vectors, singular values, and the transpose of the right singular vectors, respectively.


In [2]:
# TASK2: Check that the column spaces (not the bases) you obtained in the two ways are the
#same. (How would you check that two given bases span the same space?)

import numpy as np
from scipy.linalg import svd, qr

A = np.array([[1, -2, 3, -3], [2, -4, 9, -2], [-3, 6, -9, 9]])

# Using SVD to compute a basis for the column space
U_svd, S_svd, VT_svd = svd(A)
basis_svd = U_svd[:, :np.linalg.matrix_rank(A)]

# Using QR to compute a basis for the column space
Q_qr, R_qr = qr(A, mode='economic')
basis_qr = Q_qr

# Check if the two bases span the same space
matrix_basis_svd = np.column_stack(basis_svd)
matrix_basis_qr = np.column_stack(basis_qr)

# Check if the row spaces of the matrices are the same
if np.array_equal(np.linalg.matrix_rank(matrix_basis_svd), np.linalg.matrix_rank(matrix_basis_qr)):
    print("The column spaces obtained using SVD and QR span the same subspace.")
else:
    print("The column spaces obtained using SVD and QR do not span the same subspace.")


The column spaces obtained using SVD and QR do not span the same subspace.


# Explainlation

 If they have the same rank, it means the bases span the same subspace, and you'll get the output indicating that the column spaces are the same.

#TASK3: For a 500 × 500 random matrix, which method is faster?
in general, QR factorization is often faster for computing the column space of a matrix compared to full SVD, especially for large matrices.

# Null Space

In [3]:
#TASK1: Find the null space of the given matrix A using SVD.

import numpy as np
from scipy.linalg import svd

A = np.array([[1, -2, 9, 5, 4], [1, -1, 6, 5, -3], [-2, 0, -6, 1, -2], [4, 1, 9, 1, -9]])

# Compute the SVD of matrix A
U, S, VT = svd(A)

# Find the singular values that are close to zero (within a small tolerance)
tolerance = 1e-10  # You can adjust this tolerance based on your needs
small_singular_values = S[S < tolerance]

# The number of singular values close to zero is the dimension of the null space
null_space_dimension = len(small_singular_values)

# The right singular vectors corresponding to these singular values form a basis for the null space
null_space_basis = VT[-null_space_dimension:].T

# The null space basis spans the null space of the matrix A

# Print the basis for the null space
print("Basis for the Null Space:")
print(null_space_basis)


Basis for the Null Space:
[[ 0.73927059]
 [ 0.4887474 ]
 [-0.24642353]
 [ 0.35086228]
 [ 0.17543114]]


# TASK2: 

In [4]:
import numpy as np
from scipy.linalg import qr

A = np.array([[1, -2, 9, 5, 4], [1, -1, 6, 5, -3], [-2, 0, -6, 1, -2], [4, 1, 9, 1, -9]])

# Compute the QR factorization of the transpose of A
Q, R = qr(A.T, mode='economic')

# Extract the orthogonal complement from the Q matrix
n, m = A.shape  # n is the number of rows, m is the number of columns
orthogonal_complement = Q[:, n:]

# The orthogonal complement contains basis vectors for the null space of A

# Print the basis for the null space
print("Basis for the Null Space (Orthogonal Complement):")
print(orthogonal_complement)


Basis for the Null Space (Orthogonal Complement):
[]


In [5]:
# That the orthogonal complement  is equivalent to the null space of A, as per the fundamental theorem of linear algebra.

In [7]:
# TASK3: Check that both answers above span the same space.

import numpy as np
from scipy.linalg import svd, qr

A = np.array([[1, -2, 9, 5, 4], [1, -1, 6, 5, -3], [-2, 0, -6, 1, -2], [4, 1, 9, 1, -9]])

# Using SVD to compute a basis for the null space
U_svd, S_svd, VT_svd = svd(A)
null_space_basis_svd = VT_svd[-S_svd.size:].T

# Using QR to compute a basis for the null space
Q_qr, R_qr = qr(A.T, mode='economic')
null_space_basis_qr = Q_qr[:, A.shape[0]:]

# Check if the two bases span the same space
if null_space_basis_svd.shape[1] == 0 or null_space_basis_qr.shape[1] == 0:
    print("The null spaces are empty, and they cannot be compared.")
else:
    matrix_basis_svd = np.column_stack(null_space_basis_svd)
    matrix_basis_qr = np.column_stack(null_space_basis_qr)
    
    # Check if the row spaces of the matrices are the same
    if np.array_equal(np.linalg.matrix_rank(matrix_basis_svd), np.linalg.matrix_rank(matrix_basis_qr)):
        print("The null spaces obtained using SVD and QR span the same subspace.")
    else:
        print("The null spaces obtained using SVD and QR do not span the same subspace.")



The null spaces are empty, and they cannot be compared.


In [8]:
#  if the null spaces are empty and if they are, it informs you that they cannot be compared. If the null spaces are not empty, it checks whether they span the same subspace as previously described.